version: '3.8'

services:
  samp_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: samp-server
    ports:
      - "7777:7777"
      - "7777:7777/udp"
    restart: unless-stopped
