---
- name: Install and configure software on localhost
  hosts: localhost
  become: yes
  tasks:

    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Install dependencies for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Determine Docker Compose version and platform
      command: uname -s
      register: uname_s

    - name: Determine Docker Compose architecture
      command: uname -m
      register: uname_m

    - name: Build Docker Compose download URL
      set_fact:
        docker_compose_url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ uname_s.stdout }}-{{ uname_m.stdout }}"

    - name: Download Docker Compose
      get_url:
        url: "{{ docker_compose_url }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure Docker Compose binary is executable
      file:
        path: /usr/local/bin/docker-compose
        mode: '0755'
        state: file

    - name: Install Docker Compose command completion
      get_url:
        url: https://raw.githubusercontent.com/docker/compose/1.29.2/contrib/completion/bash/docker-compose
        dest: /etc/bash_completion.d/docker-compose

    - name: Install OpenSSH Server
      apt:
        name: openssh-server
        state: present

    - name: Start and enable OpenSSH service
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Install vsftpd (FTP Server)
      apt:
        name: vsftpd
        state: present

    - name: Start and enable vsftpd service
      service:
        name: vsftpd
        state: started
        enabled: yes

    - name: Configure vsftpd
      lineinfile:
        path: /etc/vsftpd.conf
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      with_items:
        - { regexp: '^#?local_enable', line: 'local_enable=YES' }
        - { regexp: '^#?write_enable', line: 'write_enable=YES' }
        - { regexp: '^#?chroot_local_user', line: 'chroot_local_user=YES' }
        - { regexp: '^#?allow_writeable_chroot', line: 'allow_writeable_chroot=YES' }

    - name: Restart vsftpd to apply configuration changes
      service:
        name: vsftpd
        state: restarted

    - name: Install rsync
      apt:
        name: rsync
        state: present

    - name: Install cron
      apt:
        name: cron
        state: present

    - name: Start and enable cron service
      service:
        name: cron
        state: started
        enabled: yes

    - name: Install dos2unix
      apt:
        name: dos2unix
        state: present
